version: '2'
services:
    signaturegen-app:
        image: signaturegen
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://signaturegen-mysql:3306/signaturegen?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    signaturegen-mysql:
        extends:
            file: mysql.yml
            service: signaturegen-mysql
